"""
LLM interfaces and providers (Google Gemini, Local Ollama, and Mock LLM).
"""

from abc import ABC, abstractmethod
import json
import os
from typing import Any, Dict, Generator, Optional
import urllib.request
import urllib.error


class BaseLLM(ABC):
    """Abstract base class for Large Language Models."""

    @abstractmethod
    def generate(
        self,
        system_prompt: str,
        user_prompt: str,
        max_tokens: int = 1024,
        temperature: float = 0.1,
    ) -> str:
        """Generate text completion from prompts."""
        pass


class GeminiLLM(BaseLLM):
    """Google Gemini LLM wrapper using google-generativeai."""

    def __init__(
        self,
        model_name: str = "gemini-1.5-flash",
        api_key: Optional[str] = None,
    ):
        self.model_name = model_name
        self.api_key = api_key or os.environ.get("GEMINI_API_KEY")
        if not self.api_key:
            raise ValueError("GEMINI_API_KEY is required for GeminiLLM.")

        try:
            import google.generativeai as genai
            genai.configure(api_key=self.api_key)
            self.client = genai
        except ImportError:
            raise ImportError("google-generativeai package missing. Run `pip install google-generativeai`.")

    def generate(
        self,
        system_prompt: str,
        user_prompt: str,
        max_tokens: int = 1024,
        temperature: float = 0.1,
    ) -> str:
        model = self.client.GenerativeModel(
            model_name=self.model_name,
            system_instruction=system_prompt,
            generation_config=self.client.types.GenerationConfig(
                max_output_tokens=max_tokens,
                temperature=temperature,
            ),
        )
        response = model.generate_content(user_prompt)
        return response.text if response.text else ""


class OllamaLLM(BaseLLM):
    """Local Ollama LLM provider (e.g., llama3, mistral, phi3)."""

    def __init__(
        self,
        model_name: str = "llama3:latest",
        host: str = "http://localhost:11434",
    ):
        self.model_name = model_name
        self.host = host.rstrip("/")

    def generate(
        self,
        system_prompt: str,
        user_prompt: str,
        max_tokens: int = 1024,
        temperature: float = 0.1,
    ) -> str:
        url = f"{self.host}/api/generate"
        payload = {
            "model": self.model_name,
            "system": system_prompt,
            "prompt": user_prompt,
            "stream": False,
            "options": {
                "num_predict": max_tokens,
                "temperature": temperature,
            },
        }
        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            url,
            data=data,
            headers={"Content-Type": "application/json"},
            method="POST",
        )

        try:
            with urllib.request.urlopen(req, timeout=120) as resp:
                resp_json = json.loads(resp.read().decode("utf-8"))
                return resp_json.get("response", "")
        except urllib.error.URLError as e:
            raise ConnectionError(
                f"Could not connect to Ollama at {self.host}. Is Ollama running? Error: {e}"
            )


class MockLLM(BaseLLM):
    """
    Deterministic Mock LLM for zero-network testing and automated evaluation.
    Synthesizes answers by quoting the top retrieved context chunks and appending [Source 1].
    """

    def __init__(self, prefix: str = "[Generated by MockLLM]: "):
        self.prefix = prefix

    def generate(
        self,
        system_prompt: str,
        user_prompt: str,
        max_tokens: int = 1024,
        temperature: float = 0.1,
    ) -> str:
        # Extract sources from the user_prompt if formatted by PromptBuilder
        lines = user_prompt.split("\n")
        sources_found = []
        in_source = False
        current_source_content = []

        for line in lines:
            if line.startswith("--- [Source"):
                in_source = True
                continue
            if line.startswith("=========================================") or line.startswith("User Question:"):
                in_source = False
            if in_source and line.strip():
                current_source_content.append(line.strip())

        if current_source_content:
            sample_content = " ".join(current_source_content[:3])
            if len(sample_content) > 200:
                sample_content = sample_content[:200] + "..."
            return f"{self.prefix}According to the verified reference documents, {sample_content} [Source 1]."
        
        return f"{self.prefix}Based on the provided documents, I do not have enough information to answer this question."
